export const UNIT_IDS = ["SI", "HR", "BA", "RS", "ME", "MK", "VO", "XK"];
export const SAVE_KEY = "sfrj1990.v1";

export const DESKS = [
  { id: "PRET", label: "Predsjedništvo" },
  { id: "SIV", label: "SIV" },
  { id: "SKJ", label: "SKJ" },
  { id: "REPUBLIKE", label: "Republike", readonly: true },
];

export const STAT_BARS = [
  { key: "living_standard", label: "Životni standard" },
  { key: "nationalist_heat", label: "Nacionalistička vrućina", kind: "heat" },
  { key: "yugoslav_identity", label: "Jugoslavenski identitet" },
  { key: "skj_hold", label: "Udio SK" },
  { key: "federal_trust", label: "Savezno povjerenje", kind: "trust" },
  { key: "secession_readiness", label: "Spremnost na otcjepljenje", kind: "secession" },
  { key: "jna_presence", label: "Nazočnost JNA" },
  { key: "interethnic_tension", label: "Međunacionalna napetost", kind: "heat" },
];

export const GOV_LABELS = {
  skj_monopoly: "Monopol SK",
  reform_skj: "Reformirani SK",
  nationalist: "Nacionalistička vlada",
  coalition: "Koalicija",
  deadlock: "Blokada",
};

export const CORE_FLAGS = [
  "skj_split",
  "skj_renounced_monopoly",
  "slovenia_walkout",
  "demos_slovenia",
  "hdz_croatia",
  "sps_serbia",
  "sda_sds_hdz_bosnia",
  "krajina_log_revolution",
  "serbia_constitution_first",
  "serbia_new_constitution",
  "croatia_election_held",
  "slovenia_election_held",
  "croatian_chair_seated",
  "slovenia_invited_back",
  "slovenia_left_institutions",
  "provinces_vote_independently",
  "kosovo_boycott",
  "markovic_dinar_program",
  "to_inventory_ordered",
  "to_disarmed_slovenia",
  "to_disarmed_croatia",
  "jna_sides_with_serbia",
  "presidency_deadlock",
  "confederal_talks_open",
  "independence_slovenia_declared",
  "independence_croatia_declared",
  "ec_recognition_track",
  "player_used_emergency",
  "player_used_purge",
  "player_used_jna_threat",
  "presidency_rotation_jovic",
  "slovenia_plebiscite_yes",
  "mesic_seated",
  "slice_filed_federation",
  "slice_filed_rump",
  "slice_filed_confederal",
  "slice_filed_separation",
  "skj_confederated",
  "skj_federal_successor",
  "markovic_mandate_strong",
  "markovic_starved",
  "markovic_list_founded",
  "competence_shifted",
  "federal_election_law",
  "slovenia_federal_reply_failed",
  "sovereignty_texts_filed",
  "federal_observers_si",
  "multiparty_wave",
  "imf_standby_active",
  "customs_war_active",
  "customs_war_resolved",
  "pakrac_standoff",
  "pakrac_defused",
  "belgrade_march_tanks",
  "belgrade_march_concession",
  "arsj_campaign_live",
  "ec_troika_watching",
    "croatia_act_in_court",
  "jna_garrison_posture",
  "jna_mobilization_alert",
  "jna_political_weight",
  "jna_civilian_chain",
  "siv_austerity_stance",
  "siv_stimulus_stance",
  "siv_cabinet_pressure",
  "presidency_mediation_active",
  "presidency_hardline",
  "presidency_quorum_guard",
  "ssup_soft_line",
  "ssup_hard_line",
  "sdb_civilian_leash",
  "ssp_ec_track",
  "ssp_quiet_demarche",
  "finance_transfers_open",
  "finance_transfer_freeze",
  "finance_imf_aligned",
  "talked_markovic",
  "talked_kadijevic",
  "talked_jovic",
  "talked_mesic",
  "talked_drnovsek",
  "dialogue_markovic_teeth",
  "dialogue_markovic_starve",
  "dialogue_kadijevic_civilian",
  "dialogue_kadijevic_alert",
  "dialogue_kadijevic_serbia",
  "dialogue_jovic_bind",
  "dialogue_jovic_serbia",
  "dialogue_jovic_defer",
  "dialogue_mesic_seat",
  "dialogue_mesic_block",
  "dialogue_mesic_confederal",
  "dialogue_drnovsek_invite",
  "dialogue_drnovsek_pressure",
  "desk_event_jna_seen",
  "desk_event_siv_seen",
  "desk_event_ssup_seen",
  "desk_event_pret_seen",
  "desk_event_to_seen",
  "desk_event_nby_seen",
  "desk_event_finance_customs_seen",
  "desk_event_ssp_pleb_seen",
  "desk_event_to_pakrac_seen",
  "to_coordinate_posture",
  "to_inventory_push",
  "to_republic_hold",
  "to_quiet_audit",
  "nby_tight_dinar",
  "nby_loose_credit",
  "nby_fragment_risk",
  "nby_reserves_held",
  "talked_kucan",
  "talked_tudman",
  "talked_markovic_late",
  "talked_kadijevic_late",
  "dialogue_markovic_nby",
  "dialogue_markovic_nby_soft",
  "dialogue_markovic_starve_tail",
  "dialogue_markovic_customs",
  "dialogue_markovic_imf",
  "dialogue_markovic_resign_hint",
  "dialogue_kadijevic_to",
  "dialogue_kadijevic_bound",
  "dialogue_kadijevic_winter",
  "dialogue_kadijevic_disarm",
  "dialogue_kadijevic_serbia_late",
  "dialogue_jovic_conf",
  "dialogue_jovic_conf_wait",
  "dialogue_mesic_late",
  "dialogue_drnovsek_observers",
  "dialogue_kucan_conf",
  "dialogue_kucan_to",
  "dialogue_kucan_to_done",
  "dialogue_kucan_press",
  "dialogue_kucan_press_done",
  "dialogue_tudman_mediate",
  "dialogue_tudman_sov",
  "dialogue_tudman_hard",
  "ssup_observe_line",
  "sdb_leash_tight",
  "sdb_files_shared",
  "ssup_election_watch",
  "ssup_knin_watch",
  "dialogue_kucan_charter",
  "dialogue_kucan_revisit",
  "dialogue_jovic_revisit",
  "dialogue_markovic_revisit",
  "dialogue_mesic_revisit",
  "dialogue_tudman_revisit",
  "confederal_stack_memo",
  "desk_event_ssup_election_seen",
  "desk_event_sdb_sov_seen",
  "desk_event_conf_stack_seen",
  "desk_event_ssup_pleb_seen",
  "desk_event_pret_pleb_seen",
  "desk_event_sdb_may_seen",
  "justice_constitutional_line",
  "justice_arbitrate_line",
  "justice_hard_line",
  "justice_rule_memo",
  "desk_event_justice_seen",
  "desk_event_justice_may_seen",
  "desk_event_justice_votes_seen",
  "desk_event_ssp_open_seen",
  "desk_event_drnovsek_spring_seen",
  "desk_event_conflict_warn_seen",
  "desk_event_fer_may_seen",
  "desk_conflict_soft_lock",
  "desk_conflict_hard_conf",
  "dialogue_drnovsek_congress",
  "dialogue_drnovsek_spring",
  "dialogue_drnovsek_eve",
  "skj_soft_federation",
  "skj_hard_unity",
  "skj_cedes_to_siv",
  "skj_dissolved",
  "desk_event_skj_congress_seen",
  "desk_event_skj_election_seen",
  "desk_event_skj_spring_seen",
  "desk_event_skj_memo_seen",
  "desk_event_ssp_ec_seen",
  "desk_event_bih_voice_seen",
  "desk_event_mk_voice_seen",
  "desk_event_attention_may_seen",
  "republic_voice_bih_seen",
  "republic_voice_mk_seen",
  "confederal_skj_memo",
  "talked_bogicevic",
  "talked_tupurkovski",
  "talked_racan",
  "dialogue_bogicevic_mediate",
  "dialogue_bogicevic_quorum",
  "dialogue_bogicevic_bloc",
  "dialogue_tupurkovski_conf",
  "dialogue_tupurkovski_ec",
  "dialogue_tupurkovski_quiet",
  "dialogue_racan_soft",
  "dialogue_racan_cede",
  "dialogue_racan_dissolve",
  "dialogue_jovic_skj",
  "assembly_open",
  "assembly_stalled",
  "assembly_rubber_stamp",
  "assembly_quorum_ok",
  "assembly_paralysis_risk",
  "fer_trade_open",
  "fer_imf_line",
  "fer_customs_hard",
  "fer_customs_eased",
  "fer_ec_note",
  "desk_event_assembly_open_seen",
  "desk_event_assembly_votes_seen",
  "desk_event_assembly_spring_seen",
  "desk_event_fer_open_seen",
  "desk_event_fer_autumn_seen",
  "desk_event_me_voice_seen",
  "desk_event_gligorov_voice_seen",
  "desk_event_izetbegovic_gate_seen",
  "republic_voice_me_seen",
  "republic_voice_gligorov_seen",
  "me_soft_federation",
  "me_serbia_bloc",
  "me_quorum_guard",
  "talked_gligorov",
  "talked_bucin",
  "talked_izetbegovic",
  "dialogue_gligorov_conf",
  "dialogue_gligorov_ec",
  "dialogue_gligorov_refuse_ig",
  "gligorov_refused_ig_frame",
  "dialogue_bucin_soft",
  "dialogue_bucin_bloc",
  "dialogue_bucin_quorum",
  "dialogue_izetbegovic_mediate",
  "dialogue_izetbegovic_refuse_ig",
  "dialogue_izetbegovic_quiet",
  "izetbegovic_refused_ig_frame",
  "fond_open_south",
  "fond_freeze",
  "fond_target_mk_me",
  "fond_politicized",
  "siv_fond_bind",
  "jna_quiet_redistribute",
  "presidency_south_balance",
  "confederal_fond_memo",
  "desk_event_fond_open_seen",
  "desk_event_fond_autumn_seen",
  "desk_event_fond_spring_seen",
  "desk_event_fond_memo_seen",
  "desk_event_jna_quiet_seen",
  "desk_event_siv_fond_seen",
  "desk_event_presidency_south_seen",
  "desk_event_bulatovic_voice_seen",
  "republic_voice_bulatovic_seen",
  "talked_bulatovic",
  "dialogue_bulatovic_soft",
  "dialogue_bulatovic_bloc",
  "dialogue_bulatovic_fond",
  "dialogue_markovic_fond",
  "ssrn_mass_front",
  "ssrn_civic_forum",
  "ssrn_party_capture",
  "ssrn_paralyzed",
  "ssrn_siv_bind",
  "ssp_isolation",
  "ssp_nam_bridge",
  "finance_target",
  "finance_soft_corridor",
  "confederal_ssrn_memo",
  "desk_event_ssrn_open_seen",
  "desk_event_ssrn_civic_seen",
  "desk_event_ssrn_party_seen",
  "desk_event_ssrn_pleb_seen",
  "desk_event_ssrn_spring_seen",
  "desk_event_ssrn_memo_seen",
  "desk_event_finance_target_seen",
  "desk_event_ssp_isolation_seen",
  "talked_mesic_late",
  "talked_jovic_late",
  "dialogue_mesic_late_duty",
  "dialogue_mesic_late_leverage",
  "dialogue_mesic_late_conf",
  "dialogue_jovic_late_quorum",
  "dialogue_jovic_late_bloc",
  "dialogue_jovic_late_ssrn",
  "dialogue_markovic_ssrn",
  "ssip_ec_channel",
  "ssip_nonaligned_hold",
  "ssip_bilateral_quiet",
  "ssip_paralyzed",
  "ssip_siv_bind",
  "ssip_fer_couple",
  "to_shared_reserve",
  "to_nby_liaison",
  "nby_imf_align",
  "nby_diplomatic_fx",
  "confederal_ssip_memo",
  "desk_event_ssip_open_seen",
  "desk_event_ssip_siv_seen",
  "desk_event_ssip_embassy_seen",
  "desk_event_ssip_nam_seen",
  "desk_event_ssip_pleb_seen",
  "desk_event_ssip_spring_seen",
  "desk_event_ssip_memo_seen",
  "desk_event_to_nby_couple_seen",
  "talked_loncar",
  "dialogue_loncar_ec",
  "dialogue_loncar_nam",
  "dialogue_loncar_bilateral",
  "dialogue_loncar_siv",
  "dialogue_markovic_ssip",
  "const_court_docket_open",
  "const_court_stalled",
  "const_court_yields",
  "const_court_bind_justice",
  "const_court_soft_memo",
  "const_court_annul_hard",
  "justice_refer_court",
  "justice_court_bind",
  "ssup_docket_watch",
  "ssup_court_liaison",
  "confederal_const_court_memo",
  "desk_event_const_court_open_seen",
  "desk_event_justice_refer_seen",
  "desk_event_ssup_docket_seen",
  "desk_event_const_court_autumn_seen",
  "desk_event_justice_bind_seen",
  "desk_event_const_court_pleb_seen",
  "desk_event_const_court_spring_seen",
  "desk_event_const_court_memo_seen",
  "talked_buzadzic",
  "dialogue_buzadzic_docket",
  "dialogue_buzadzic_bind",
  "dialogue_buzadzic_stall",
  "dialogue_buzadzic_revisit",
  "dialogue_markovic_const_court",
  "provinces_bloc_tight",
  "provinces_observe",
  "provinces_mediate",
  "presidency_province_voice",
  "presidency_province_quorum",
  "ssup_province_dossier",
  "confederal_provinces_memo",
  "desk_event_provinces_open_seen",
  "desk_event_provinces_spring_seen",
  "desk_event_provinces_autumn_seen",
  "desk_event_ssup_province_dossier_seen",
  "desk_event_provinces_pleb_seen",
  "desk_event_presidency_province_quorum_seen",
  "desk_event_provinces_spring91_seen",
  "desk_event_provinces_memo_seen",
  "talked_bajramovic",
  "talked_kostic",
  "dialogue_bajramovic_indep",
  "dialogue_bajramovic_bloc",
  "dialogue_bajramovic_mediate",
  "dialogue_kostic_indep",
  "dialogue_kostic_observe",
  "dialogue_kostic_bloc",
  "dialogue_markovic_provinces",
  "ssno_doctrine_federal",
  "ssno_inventory_audit",
  "ssno_to_coordinate",
  "ssno_chair_counsel",
  "ssno_quiet_paper",
  "ssno_siv_bind",
  "ssno_paralyzed",
  "jna_ssno_doctrine_bind",
  "jna_ssno_inventory_channel",
  "to_ssno_liaison",
  "to_ssno_shared_paper",
  "confederal_ssno_memo",
  "desk_event_ssno_open_seen",
  "desk_event_ssno_spring_seen",
  "desk_event_ssno_autumn_seen",
  "desk_event_jna_ssno_bind_seen",
  "desk_event_ssno_pleb_seen",
  "desk_event_to_ssno_liaison_seen",
  "desk_event_ssno_spring91_seen",
  "desk_event_ssno_memo_seen",
  "dialogue_kadijevic_ssno",
  "dialogue_kadijevic_ssno_late",
  "dialogue_markovic_ssno",
  "sdb_observe_line",
  "sdb_dossier_channel",
  "sdb_knin_watch",
  "sdb_ssup_bind",
  "sdb_siv_bind",
  "sdb_quiet_paper",
  "confederal_sdb_memo",
  "desk_event_sdb_open_seen",
  "desk_event_sdb_spring_seen",
  "desk_event_sdb_autumn_seen",
  "desk_event_ssup_sdb_bind_seen",
  "desk_event_sdb_pleb_seen",
  "desk_event_siv_sdb_leash_seen",
  "desk_event_sdb_spring91_seen",
  "desk_event_sdb_memo_seen",
  "dialogue_gracanin",
  "dialogue_gracanin_leash",
  "dialogue_markovic_sdb",
  "talked_gracanin",
  "ssup_sdb_liaison",
  "ssup_sdb_channel",
  "labor_social_peace",
  "labor_strike_cool",
  "labor_reform_support",
  "labor_wage_corridor",
  "labor_harden_line",
  "labor_siv_bind",
  "labor_quiet_paper",
  "confederal_labor_memo",
  "desk_event_labor_open_seen",
  "desk_event_labor_spring_seen",
  "desk_event_labor_autumn_seen",
  "desk_event_finance_labor_bind_seen",
  "desk_event_labor_pleb_seen",
  "desk_event_ssrn_labor_liaison_seen",
  "desk_event_labor_spring91_seen",
  "desk_event_labor_memo_seen",
  "dialogue_gacic",
  "dialogue_gacic_peace",
  "dialogue_markovic_labor",
  "talked_gacic",
  "finance_labor_liaison",
  "finance_labor_corridor",
  "ssrn_labor_liaison",
  "ssrn_labor_channel",
  "agriculture_food_security",
  "agriculture_procurement_soft",
  "agriculture_farm_relief",
  "agriculture_reform_support",
  "agriculture_harden_quota",
  "agriculture_siv_bind",
  "agriculture_quiet_paper",
  "confederal_agriculture_memo",
  "desk_event_agriculture_open_seen",
  "desk_event_agriculture_spring_seen",
  "desk_event_agriculture_autumn_seen",
  "desk_event_finance_agriculture_bind_seen",
  "desk_event_agriculture_pleb_seen",
  "desk_event_fond_agriculture_liaison_seen",
  "desk_event_agriculture_spring91_seen",
  "desk_event_agriculture_memo_seen",
  "dialogue_mirjanic",
  "dialogue_mirjanic_food",
  "dialogue_markovic_agriculture",
  "talked_mirjanic",
  "finance_agriculture_liaison",
  "finance_agriculture_corridor",
  "fond_agriculture_liaison",
  "fond_agriculture_food",
  "industry_grid_stable",
  "industry_plant_soft",
  "industry_output_support",
  "industry_reform_support",
  "industry_harden_ration",
  "industry_siv_bind",
  "industry_quiet_paper",
  "confederal_industry_memo",
  "desk_event_industry_open_seen",
  "desk_event_industry_spring_seen",
  "desk_event_industry_autumn_seen",
  "desk_event_finance_industry_bind_seen",
  "desk_event_industry_pleb_seen",
  "desk_event_fer_industry_liaison_seen",
  "desk_event_industry_spring91_seen",
  "desk_event_industry_memo_seen",
  "dialogue_santo",
  "dialogue_santo_grid",
  "dialogue_markovic_industry",
  "talked_santo",
  "finance_industry_liaison",
  "finance_industry_corridor",
  "fer_industry_liaison",
  "fer_industry_energy",
  "trade_market_calm",
  "trade_shelf_soft",
  "trade_price_corridor",
  "trade_reform_support",
  "trade_harden_controls",
  "trade_siv_bind",
  "trade_quiet_paper",
  "confederal_trade_memo",
  "desk_event_trade_open_seen",
  "desk_event_trade_spring_seen",
  "desk_event_trade_autumn_seen",
  "desk_event_finance_trade_bind_seen",
  "desk_event_trade_pleb_seen",
  "desk_event_fer_trade_liaison_seen",
  "desk_event_trade_spring91_seen",
  "desk_event_trade_memo_seen",
  "dialogue_nazmi",
  "dialogue_nazmi_calm",
  "dialogue_markovic_trade",
  "talked_nazmi",
  "finance_trade_liaison",
  "finance_trade_corridor",
  "fer_trade_liaison",
  "fer_trade_desk",
];

const BOOLEAN_FEDERAL = new Set(["skj_leading_role"]);

export function clamp(n, lo = 0, hi = 100) {
  const x = Number(n);
  if (Number.isNaN(x)) return lo;
  return Math.max(lo, Math.min(hi, Math.round(x)));
}

export function defaultFederal() {
  return {
    legitimacy: 62,
    presidency_cohesion: 48,
    siv_authority: 56,
    skj_unity: 38,
    skj_leading_role: true,
    federal_budget: 44,
    hard_currency: 36,
    inflation: 68,
    reform_momentum: 40,
    imf_pressure: 52,
    jna_cohesion: 74,
    jna_obedience_to_civilian: 58,
    sdb_control: 54,
    labor_peace: 50,
    food_security: 50,
    energy_security: 50,
    internal_market: 50,
    assembly_function: 50,
    inter_republic_trade: 57,
    international_standing: 49,
    war_risk: 14,
    clock: "1990-01-20",
    turn: 0,
  };
}

export function defaultPresidency() {
  return {
    SI: true,
    HR: true,
    BA: true,
    RS: true,
    ME: true,
    MK: true,
    VO: true,
    XK: true,
  };
}

export function emptyFlags() {
  const flags = {};
  for (const id of CORE_FLAGS) flags[id] = false;
  return flags;
}

export function createNewState(catalogs) {
  const units = {};
  for (const u of catalogs.units.units) {
    units[u.id] = {
      id: u.id,
      name: u.name,
      name_local: u.name_local,
      type: u.type,
      capital: u.capital,
      color: u.color,
      ...u.stats,
      government_type: u.government_type,
      election_held: u.election_held,
      planned_move: u.planned_move,
      federal_control: u.stats.federal_trust ?? 40,
      jna_threatened: false,
    };
  }

  const parties = catalogs.parties.parties.map((p) => ({ ...p, ideology: [...p.ideology] }));
  const agencies = catalogs.agencies.agencies.map((a) => ({ ...a }));

  return {
    federal: defaultFederal(),
    presidency: defaultPresidency(),
    units,
    parties,
    agencies,
    flags: emptyFlags(),
    log: [],
    queue: [],
    resolved: [],
    spawned: [],
    desk: "SKJ",
    selectedUnit: "SI",
    charter_signatures: 0,
    ended: false,
    mapMode: "raskol",
    reform_actions: 0,
    reform_month: "",
    reformFamily: "skj",
    lastMonthlyReport: null,
    pressureLog: [],
    desks: {},
    desk_actions: 0,
    desk_month: "",
    dialogue_done: [],
    dialogue_visits: {},
    activeDialogue: null,
    attention_left: 0,
    attention_month: "",
    attention_spent_desks: 0,
    attention_spent_reforms: 0,
    save_schema: 17,
  };
}

export function saveState(state) {
  localStorage.setItem(SAVE_KEY, JSON.stringify(state));
}

export function loadSave() {
  try {
    const raw = localStorage.getItem(SAVE_KEY);
    if (!raw) return null;
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export function hasSave() {
  return !!localStorage.getItem(SAVE_KEY);
}

export function pathGet(state, path) {
  if (path === "flags" || path.startsWith("flags.")) {
    const flag = path.split(".")[1];
    return flag ? !!state.flags[flag] : state.flags;
  }
  const parts = path.split(".");
  if (parts[0] === "federal") return state.federal[parts[1]];
  if (parts[0] === "presidency") return state.presidency[parts[1]];
  if (UNIT_IDS.includes(parts[0])) return state.units[parts[0]][parts[1]];
  if (parts[0] === "desks" && parts[1] && state.desks?.[parts[1]]) {
    return parts[2] ? state.desks[parts[1]][parts[2]] : state.desks[parts[1]];
  }
  if (Object.prototype.hasOwnProperty.call(state.federal, parts[0]) && parts.length === 1) {
    return state.federal[parts[0]];
  }
  return undefined;
}

export function pathSet(state, path, value) {
  const parts = path.split(".");
  if (parts[0] === "federal") {
    const key = parts[1];
    if (BOOLEAN_FEDERAL.has(key)) state.federal[key] = !!value && value !== 0;
    else state.federal[key] = clamp(value);
    return;
  }
  if (parts[0] === "presidency") {
    state.presidency[parts[1]] = !!value;
    return;
  }
  if (UNIT_IDS.includes(parts[0])) {
    const key = parts[1];
    const cur = state.units[parts[0]][key];
    if (typeof cur === "boolean") state.units[parts[0]][key] = !!value && value !== 0;
    else if (typeof cur === "string") state.units[parts[0]][key] = String(value);
    else state.units[parts[0]][key] = clamp(value);
    return;
  }
  if (Object.prototype.hasOwnProperty.call(state.federal, parts[0]) && parts.length === 1) {
    pathSet(state, `federal.${parts[0]}`, value);
  }
}

export function pathAdd(state, path, delta) {
  const cur = pathGet(state, path);
  if (typeof cur === "boolean") {
    pathSet(state, path, delta);
    return;
  }
  if (typeof cur === "number") pathSet(state, path, cur + Number(delta));
  else pathSet(state, path, delta);
}

export function formatDate(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
  ];
  return `${d} ${months[m - 1]} ${y}`;
}

export function monthIndex(iso) {
  const [y, m] = iso.split("-").map(Number);
  return (y - 1990) * 12 + (m - 1);
}

export function humanize(id) {
  return String(id || "")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export function presidencyTally(state) {
  return UNIT_IDS.reduce((n, id) => n + (state.presidency[id] ? 1 : 0), 0);
}
